// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'conversation': string;
  'conversation__content': string;
  'conversation__dialogue': string;
  'conversation__feedback': string;
}
export const cssExports: CssExports;
export default cssExports;
