// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'registrationSuccess': string;
  'registrationSuccess__logo': string;
  'registrationSuccess__logoImage': string;
  'registrationSuccess__message': string;
  'registrationSuccess__title': string;
}
export const cssExports: CssExports;
export default cssExports;
