// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'resetPassword': string;
  'resetPassword__error': string;
  'resetPassword__form': string;
}
export const cssExports: CssExports;
export default cssExports;
