const PAYMENT_METHOD = {
  1: {
    DURATION_IN_MONTHS: 1,
    AMOUNT: 13,
    DESCRIPTION: 'MEMBRESÍA POR 1 MES.'
  },

  2: {
    DURATION_IN_MONTHS: 12,
    AMOUNT: 130,
    DESCRIPTION: 'MEMBRESÍA POR 1 AÑO.'
  },

  3: {
    DURATION_IN_MONTHS: 3,
    AMOUNT: 35,
    DESCRIPTION: 'MEMBRESÍA POR 3 MES.'
  }
}

module.exports = {
  PAYMENT_METHOD
}
