// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'button__container': string;
  'error__message': string;
  'field': string;
  'form': string;
  'input__container': string;
  'label': string;
  'message__container': string;
  'success__message': string;
}
export const cssExports: CssExports;
export default cssExports;
