// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'button__container': string;
  'field': string;
  'form': string;
  'form__container': string;
  'form__errorMessage': string;
  'form__title': string;
}
export const cssExports: CssExports;
export default cssExports;
