// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'buttons': string;
  'cancel': string;
  'disabled': string;
  'display': string;
  'editIcon': string;
  'editing': string;
  'inlineEditor': string;
  'input': string;
  'save': string;
}
export const cssExports: CssExports;
export default cssExports;
