const SET_USER: 'SET_USER' = 'SET_USER';
const CLEAR_LOAD: 'CLEAR_LOAD' = 'CLEAR_LOAD';
const SET_LOAD: 'SET_LOAD' = 'SET_LOAD';
const SIGN_OUT: 'SIGN_OUT' = 'SIGN_OUT';
const SET_COURSE_CACHE: 'SET_COURSE_CACHE' = 'SET_COURSE_CACHE';
const SET_COURSES_CACHE: 'SET_COURSES_CACHE' = 'SET_COURSES_CACHE';
const CLEAN_CACHE: 'CLEAN_CACHE' = 'CLEAN_CACHE';
const SET_LIBRARY: 'SET_LIBRARY' = 'SET_LIBRARY';

export {
  SET_USER,
  CLEAR_LOAD,
  SET_LOAD,
  SIGN_OUT,
  SET_COURSE_CACHE,
  SET_COURSES_CACHE,
  CLEAN_CACHE,
  SET_LIBRARY
};
