// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'aside': string;
  'aside__button': string;
  'aside__element': string;
  'aside__lession': string;
  'aside__lession_title': string;
  'aside__lessions': string;
  'aside__padlock': string;
  'aside__title': string;
  'aside__word': string;
  'aside__words': string;
  'button__container': string;
  'display': string;
  'hide': string;
  'hide__default': string;
  'slideInAside': string;
  'slideOutAside': string;
  'tutorial__title': string;
  'word__display': string;
}
export const cssExports: CssExports;
export default cssExports;
