// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'modal__button': string;
  'modal__container': string;
  'modal__content': string;
  'modal__text': string;
}
export const cssExports: CssExports;
export default cssExports;
