// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'contact': string;
  'contact__contact': string;
  'contact__container': string;
  'contact__header': string;
}
export const cssExports: CssExports;
export default cssExports;
