// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'course': string;
  'course__arrowLeft': string;
  'course__arrowRight': string;
  'course__bar': string;
  'course__container': string;
  'course__content': string;
  'course__content_container': string;
  'course__content_text': string;
  'course__englishWord': string;
  'course__englishWord_container': string;
  'course__feedback': string;
  'course__image': string;
  'course__lession_container': string;
  'course__message': string;
  'course__modal': string;
  'course__modalMessage': string;
  'course__modalMessageButton': string;
  'course__modalText': string;
  'course__modalTitle': string;
  'course__progress': string;
  'course__progress_container': string;
  'course__pronunciation': string;
  'course__save_progress': string;
  'course__save_progress_container': string;
  'course__spanishTranslation': string;
  'course__spanishTranslation_container': string;
  'course__text_grandient': string;
  'course__text_language': string;
  'course__text_lession': string;
}
export const cssExports: CssExports;
export default cssExports;
