// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'alphabet-page': string;
  'beat': string;
  'feedback': string;
  'letter': string;
  'letter-animation': string;
  'letter-grid': string;
  'song-button': string;
  'text': string;
}
export const cssExports: CssExports;
export default cssExports;
