// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'fadeInFromBottom1': string;
  'fadeInFromBottom2': string;
  'home': string;
  'home__article1': string;
  'home__article2': string;
  'home__article20': string;
  'home__article3': string;
  'home__article4': string;
  'home__banner': string;
  'home__buttons': string;
  'home__card': string;
  'home__cards': string;
  'home__circle': string;
  'home__content': string;
  'home__header': string;
  'home__header2': string;
  'home__header3': string;
  'home__image': string;
  'home__lists': string;
  'home__name': string;
  'home__wrapper': string;
  'imgAnimation': string;
  'img__animation': string;
  'img__visible': string;
}
export const cssExports: CssExports;
export default cssExports;
