// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'stats': string;
  'stats__button': string;
  'stats__container': string;
  'stats__container--hover': string;
  'stats__header': string;
  'stats__number': string;
}
export const cssExports: CssExports;
export default cssExports;
