// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'familyPlan': string;
  'familyPlan__container': string;
  'familyPlan__img': string;
  'familyPlan__link': string;
  'familyPlan__list': string;
  'familyPlan__price': string;
  'familyPlan__title': string;
  'familyPlan__titleContainer': string;
  'familyPlan__user': string;
}
export const cssExports: CssExports;
export default cssExports;
