// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'input-group': string;
  'sentence-group': string;
  'word': string;
  'word__button': string;
  'word__form': string;
  'word__list': string;
  'word__save-button': string;
  'word__search': string;
  'word__search-button': string;
  'word__sentence': string;
  'word__sentence-title': string;
}
export const cssExports: CssExports;
export default cssExports;
