// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'plan': string;
  'plan__cards': string;
  'plan__title': string;
}
export const cssExports: CssExports;
export default cssExports;
