// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'page404': string;
  'page404__container': string;
  'page404__content': string;
  'page404__subTitle': string;
  'page404__title': string;
}
export const cssExports: CssExports;
export default cssExports;
