// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'payment': string;
  'payment__card': string;
  'payment__container': string;
  'payment__cvc': string;
  'payment__errorMessage': string;
  'payment__form': string;
  'payment__input': string;
  'payment__input_button': string;
  'payment__inputs': string;
  'payment__inputs_container': string;
  'payment__modal': string;
  'payment__modalButton': string;
  'payment__modalIcon': string;
  'payment__modalText': string;
  'payment__subscription': string;
  'payment__title': string;
}
export const cssExports: CssExports;
export default cssExports;
