// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'payment': string;
  'payment__container': string;
  'payment__form': string;
  'payment__input': string;
  'payment__input_button': string;
  'payment__inputs': string;
  'payment__inputs_container': string;
}
export const cssExports: CssExports;
export default cssExports;
