// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'languageSwitcher': string;
  'languageSwitcher__arrow': string;
  'languageSwitcher__button': string;
  'languageSwitcher__dropdown': string;
  'languageSwitcher__flag': string;
  'languageSwitcher__name': string;
  'languageSwitcher__option': string;
  'languageSwitcher__optionFlag': string;
  'languageSwitcher__optionName': string;
  'languageSwitcher__option_active': string;
}
export const cssExports: CssExports;
export default cssExports;
