import { ENDPOINT } from '../../tools/consts';

const avoidTokenEndpoints: string[] = [
  ENDPOINT.CONTANCT,
  ENDPOINT.SUSCRIBETE,
  ENDPOINT.LOGIN,
  ENDPOINT.SING_UP
];

const tokenFromHeaderEndpoints: string[] = [
  ENDPOINT.RESET_PASSWORD_AUTH,
  ENDPOINT.RESET_PASSWORD,
  ENDPOINT.ACTIVE_ACCOUNT,
];

const tokenFromCookieEndpoints: string[] = [
  ENDPOINT.AUTH,
  ENDPOINT.SING_OUT,
  ENDPOINT.STUDENT_COURSES,
  ENDPOINT.STUDENT_COURSE_PROGRESS,
  ENDPOINT.STUDENT_SENTENCE,
  ENDPOINT.STUDENT_INVOICE,
  ENDPOINT.STUDENT_UPDATE,
  ENDPOINT.STUDENT_TERMS,
  ENDPOINT.LIBRARY,
  ENDPOINT.AZUL_PAYMENT,
  ENDPOINT.STUDENT_TUTORIAL,
  ENDPOINT.PAYPAL,
  ENDPOINT.STUDENT_DELETE_ACCOUNT,
  ENDPOINT.STUDENT_RATING,
];

const removeTokenAndAvoidEndpoint: string[] = [
  ENDPOINT.AUTH,
  ENDPOINT.REGISTER,
  ENDPOINT.STUDENT_COURSES_DEMO,
  ENDPOINT.STUDENT_COURSE_DEMO,
  ENDPOINT.SEND_EMAIL_RESET_PASSWORD
];

export {
  avoidTokenEndpoints,
  tokenFromHeaderEndpoints,
  tokenFromCookieEndpoints,
  removeTokenAndAvoidEndpoint
}