// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'table': string;
  'table__td': string;
  'table__th': string;
  'table__thead': string;
  'table__tr': string;
}
export const cssExports: CssExports;
export default cssExports;
