// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'courses': string;
  'courses__background': string;
  'courses__button': string;
  'courses__container': string;
  'courses__header': string;
  'courses__items': string;
  'courses__picture': string;
  'courses__progress': string;
  'courses__progress_chart': string;
  'courses__progress_circle': string;
  'courses__progress_circle_bg': string;
  'courses__progress_circular_chart': string;
  'courses__progress_percentage': string;
  'courses__text': string;
  'courses__title': string;
  'progress': string;
}
export const cssExports: CssExports;
export default cssExports;
