// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'capacityIndicator': string;
  'controls': string;
  'courseSelector': string;
  'dragHandle': string;
  'dragOver': string;
  'dragging': string;
  'draggingOver': string;
  'dropZone': string;
  'englishWord': string;
  'header': string;
  'lesson': string;
  'lessonManagement': string;
  'lessonTitle': string;
  'lessonsContainer': string;
  'loading': string;
  'noData': string;
  'saveButton': string;
  'spanishTranslation': string;
  'wordCard': string;
  'wordContent': string;
  'wordsList': string;
}
export const cssExports: CssExports;
export default cssExports;
