// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'card': string;
  'card__characteristic': string;
  'card__characteristicText': string;
  'card__characteristics': string;
  'card__check': string;
  'card__checkmarPopular': string;
  'card__checkmark': string;
  'card__link': string;
  'card__popular': string;
  'card__popularContainer': string;
  'card__popularStar': string;
  'card__popularTitle': string;
  'card__price': string;
  'card__priceTitle': string;
  'card__priceValue': string;
  'card__priceValueDOP': string;
  'card__title': string;
  'card__uniTime': string;
}
export const cssExports: CssExports;
export default cssExports;
