// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'footer': string;
  'footer__address': string;
  'footer__item': string;
  'footer__items': string;
  'footer__title': string;
}
export const cssExports: CssExports;
export default cssExports;
