// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'sound': string;
  'tips': string;
  'tips__container': string;
  'tips__header': string;
  'tips__image': string;
  'tips__speech': string;
}
export const cssExports: CssExports;
export default cssExports;
