// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'card': string;
  'card__content': string;
  'card__description': string;
  'card__header': string;
  'card__photo': string;
  'card__tag': string;
  'card__userName': string;
}
export const cssExports: CssExports;
export default cssExports;
