// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'avatar': string;
  'avatar__image': string;
  'avatar__input': string;
}
export const cssExports: CssExports;
export default cssExports;
