// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'contact': string;
  'contact__info': string;
  'contact__infos': string;
  'fag': string;
  'fag__container': string;
  'fag__content': string;
  'fag__country': string;
  'fag__figure': string;
  'fag__image': string;
  'fag__name': string;
  'fag__question': string;
  'fag__text': string;
  'fag__texts': string;
  'fag__title': string;
  'form': string;
  'form__container': string;
}
export const cssExports: CssExports;
export default cssExports;
