// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'form': string;
  'form__contact': string;
  'form__container': string;
}
export const cssExports: CssExports;
export default cssExports;
