// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'modal': string;
  'modal__button': string;
  'modal__icon': string;
  'modal__text': string;
}
export const cssExports: CssExports;
export default cssExports;
