// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'home': string;
  'home__block': string;
  'home__content': string;
  'home__discord': string;
  'home__discordIcon': string;
  'home__image': string;
  'home__title': string;
  'imgAnimation': string;
  'img__animation': string;
}
export const cssExports: CssExports;
export default cssExports;
