// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'loading': string;
  'loading__header': string;
  'loading__image': string;
}
export const cssExports: CssExports;
export default cssExports;
