// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'terms': string;
  'terms__center': string;
  'terms__container': string;
}
export const cssExports: CssExports;
export default cssExports;
