// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'profile__cover': string;
  'profile__content': string;
  'profile': string;
  'profile__avatar': string;
  'profile__button': string;
  'profile__container': string;
  'profile__info': string;
  'profile__info_container': string;
}
export const cssExports: CssExports;
export default cssExports;
