// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'floating': string;
  'profile': string;
  'profile__background': string;
  'profile__button': string;
  'profile__buttonContainer': string;
  'profile__content': string;
  'profile__info': string;
  'profile__title': string;
}
export const cssExports: CssExports;
export default cssExports;
