// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'login': string;
  'login__error': string;
  'login__link': string;
}
export const cssExports: CssExports;
export default cssExports;
