// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'fadeInFromBottom1': string;
  'fadeInFromBottom2': string;
  'home': string;
  'home__block': string;
  'home__buttons': string;
  'home__circle': string;
  'home__content': string;
  'home__image': string;
  'home__wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
