// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'errorConnection': string;
  'errorConnection__text': string;
  'errorConnection__title': string;
}
export const cssExports: CssExports;
export default cssExports;
