// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'sound': string;
  'sound__icon': string;
}
export const cssExports: CssExports;
export default cssExports;
