// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'aside': string;
  'aside__aside': string;
  'aside__focus': string;
  'aside__section': string;
  'aside__tab': string;
  'aside__tabs': string;
}
export const cssExports: CssExports;
export default cssExports;
