// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'backButton': string;
  'buttons': string;
  'cancelButton': string;
  'cancelSubscription': string;
  'confirmButton': string;
  'confirmDialog': string;
  'reasonInput': string;
}
export const cssExports: CssExports;
export default cssExports;
