// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'home': string;
  'home__block': string;
  'home__content': string;
  'home__header': string;
  'home__header2': string;
  'home__lists': string;
  'home__wrapper': string;
  'img__animation': string;
}
export const cssExports: CssExports;
export default cssExports;
