// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'navigator': string;
  'navigator__container': string;
  'navigator__hamburger': string;
  'navigator__line': string;
  'navigator__link': string;
  'navigator__links': string;
  'navigator__logo': string;
  'navigator__open': string;
  'navigator__picture': string;
  'navigator__tab': string;
  'navigator__tabMobile': string;
  'navigator__target': string;
  'navigator__user': string;
  'navigator__user_name': string;
}
export const cssExports: CssExports;
export default cssExports;
