// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'modal__button': string;
  'modal__message': string;
  'modal__title': string;
}
export const cssExports: CssExports;
export default cssExports;
