// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'beat': string;
  'speech': string;
  'speech__beatAnimation': string;
  'speech__feedback': string;
  'speech__icon': string;
}
export const cssExports: CssExports;
export default cssExports;
